### ISSUE TITLE
Minimal GCP resource instance failing during reconciliation

### ISSUE THREAD

**Issue by rathpc** [crossplane/stack-minimal-gcp#13]
After creating an instance of stack-minimal-gcp this is the status.

```yaml
status:
  conditions:
  - lastTransitionTime: "2020-02-04T17:46:28Z"
    message: 'apply failed: minimal-gcp-instance-connection/ of type servicenetworking.gcp.crossplane.io/v1alpha3,
      Kind=Connection: no matches for kind "Connection" in version "servicenetworking.gcp.crossplane.io/v1alpha3"'
    reason: Encountered an error during resource reconciliation
    status: "False"
    type: Synced
```

**Comment by jbw976** [comment]
@rathpc is reporting that this is reproducing still after building locally with #11

**Comment by rathpc** [comment]
It seems locally my build just never updated but now I am getting this error

```yaml
status:
  conditions:
  - lastTransitionTime: "2020-02-04T18:07:32Z"
    message: |-
      apply failed: minimal-gcp-instance-connection/ of type servicenetworking.gcp.crossplane.io/v1beta1, Kind=Connection: Connection.servicenetworking.gcp.crossplane.io "minimal-gcp-instance-connection" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"servicenetworking.gcp.crossplane.io/v1beta1", "kind":"Connection", "metadata":map[string]interface {}{"creationTimestamp":"2020-02-04T18:07:32Z", "generation":1, "labels":map[string]interface {}{"gcp.resourcepacks.crossplane.io/name":"minimal-gcp-instance", "gcp.resourcepacks.crossplane.io/uid":"73c217b2-5bfb-4be0-8a50-db3bee4af480"}, "name":"minimal-gcp-instance-connection", "ownerReferences":[]interface {}{map[string]interface {}{"apiVersion":"gcp.resourcepacks.crossplane.io/v1alpha1", "kind":"MinimalGCP", "name":"minimal-gcp-instance", "uid":"73c217b2-5bfb-4be0-8a50-db3bee4af480"}}, "uid":"289c666c-a9f7-420a-a1da-32ba21ce9606"}, "spec":map[string]interface {}{"networkRef":map[string]interface {}{"name":"minimal-gcp-instance-network"}, "parent":"services/servicenetworking.googleapis.com", "providerRef":map[string]interface {}{"name":"minimal-gcp-instance-gcp-provider"}, "reclaimPolicy":"Delete", "reservedPeeringRangeRefs":[]interface {}{map[string]interface {}{"name":"minimal-gcp-instance-globaladdress"}}}}: validation failure list:
      spec.forProvider in body is required
    reason: Encountered an error during resource reconciliation
    status: "False"
    type: Synced
```
