### ISSUE TITLE
GKECluster and CloudSQLInstance report: invalid character ''1'' after object key:value pair

### ISSUE THREAD

**Issue by prasek** [crossplane/stack-minimal-gcp#53]
After deploying the Wordpress sample app I get the following `Sync` message on the `GKECluster` and `CloudSQLInstance` resources:

```
status:
  conditions:
    - lastTransitionTime: '2020-05-25T21:28:48Z'
      message: 'invalid character ''1'' after object key:value pair'
      reason: Encountered an error during resource reconciliation
      status: 'False'
      type: Synced
```
